BEGIN;
INSERT INTO sync_log (started_at, status) VALUES (NOW(), 'running');
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD37-UK', 2, 400, 0, 161.98, 238.02, 238.02, 2.47, 80.99, 0.7641, 6, 212, 97.2, 204, 6, 0.94, 33.33, 200, 0.94, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{6 POTES - LIPOTIDE,3 POTES - LIPOTIDE,1 POTE - LIPOTIDE}', '{United Kingdom,United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG2-UK', 1, 296.2, 0, 80.22, 215.98, 215.98, 3.69, 80.22, 0.764, 2, 105, 98.1, 102, 2, 0.95, 50, 296.2, 0.95, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{6 POTES - LIPOTIDE,3 POTES - LIPOTIDE}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG02', 1, 220, 0, 150.07, 69.93, 69.93, 1.47, 150.07, 0.4749, 3, 316, 99.1, 271, 3, 0.32, 33.33, 220, 0.32, '{PF-JEFF (Jelly Lean),JELLY LEAN}', '{JellyLean 6 bottles}', '{United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD8-UK', 1, 200, 0, 22.16, 177.84, 177.84, 9.03, 22.16, 0.7641, 1, 29, 96.6, 27, 1, 3.45, 100, 200, 3.45, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{6 POTES - LIPOTIDE}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD60-UK', 1, 200, 0, 96.27, 103.73, 103.73, 2.08, 96.27, 0.764, 5, 126, 96, 123, 5, 0.79, 20, 200, 0.79, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{6 POTES - LIPOTIDE,3 POTES - LIPOTIDE}', '{United Kingdom,United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG10-UK', 1, 200, 0, 125.3, 74.7, 74.7, 1.6, 125.3, 0.764, 5, 164, 97, 163, 5, 0.61, 20, 200, 0.61, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{6 POTES - LIPOTIDE,3 POTES - LIPOTIDE}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD9-UK', 1, 200, 0, 138.29, 61.71, 61.71, 1.45, 138.29, 0.764, 6, 181, 96.7, 179, 6, 0.55, 16.67, 200, 0.55, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{1 POTE - LIPOTIDE,3 POTES - LIPOTIDE,6 POTES - LIPOTIDE}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG5-UK', 1, 200, 0, 158.16, 41.84, 41.84, 1.26, 158.16, 0.7641, 3, 207, 98.6, 202, 3, 0.48, 33.33, 200, 0.48, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{6 POTES - LIPOTIDE,1 POTE - LIPOTIDE}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG13-UK', 0, 0, 0, 112.31, -112.31, -112.31, 0, 0, 0.764, 2, 147, 98.6, 146, 2, 0, 0, 0, 0, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{6 POTES - LIPOTIDE}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD10-UK', 0, 0, 0, 97.03, -97.03, -97.03, 0, 0, 0.764, 1, 127, 99.2, 121, 1, 0, 0, 0, 0, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{3 POTES - LIPOTIDE}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG9-UK', 0, 0, 0, 37.44, -37.44, -37.44, 0, 0, 0.7641, 2, 49, 95.9, 49, 2, 0, 0, 0, 0, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{6 POTES - LIPOTIDE,3 POTES - LIPOTIDE}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG8-UK', 0, 0, 0, 47.37, -47.37, -47.37, 0, 0, 0.764, 0, 62, 0, 59, 0, 0, 0, 0, 0, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG7-UK', 0, 0, 0, 106.2, -106.2, -106.2, 0, 0, 0.764, 1, 139, 99.3, 137, 1, 0, 0, 0, 0, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{1 POTE - LIPOTIDE}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG6-UK', 0, 0, 0, 57.3, -57.3, -57.3, 0, 0, 0.764, 0, 75, 0, 71, 0, 0, 0, 0, 0, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG4-UK', 0, 0, 0, 88.63, -88.63, -88.63, 0, 0, 0.7641, 1, 116, 99.1, 113, 1, 0, 0, 0, 0, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{1 POTE - LIPOTIDE}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG3-UK', 0, 0, 0, 54.25, -54.25, -54.25, 0, 0, 0.7641, 1, 71, 98.6, 70, 1, 0, 0, 0, 0, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{3 POTES - LIPOTIDE}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD11-UK', 0, 0, 0, 48.9, -48.9, -48.9, 0, 0, 0.7641, 1, 64, 98.4, 63, 1, 0, 0, 0, 0, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{6 POTES - LIPOTIDE}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD42-TEC', 0, 0, 0, 29.03, -29.03, -29.03, 0, 0, 0.7639, 0, 38, 0, 38, 0, 0, 0, 0, 0, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG11-UK', 0, 0, 0, 56.54, -56.54, -56.54, 0, 0, 0.7641, 0, 74, 0, 71, 0, 0, 0, 0, 0, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD12-LIPOUK', 0, 0, 0, 23.69, -23.69, -23.69, 0, 0, 0.7642, 1, 31, 96.8, 26, 1, 0, 0, 0, 0, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{6 POTES - LIPOTIDE}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG1-UK', 0, 0, 0, 73.35, -73.35, -73.35, 0, 0, 0.7641, 1, 96, 99, 93, 1, 0, 0, 0, 0, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{1 POTE - LIPOTIDE}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD12-UK', 0, 0, 0, 91.68, -91.68, -91.68, 0, 0, 0.764, 4, 120, 96.7, 116, 4, 0, 0, 0, 0, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{3 POTES - LIPOTIDE,6 POTES - LIPOTIDE}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD8', 0, 0, 0, 47.37, -47.37, -47.37, 0, 0, 0.764, 5, 62, 91.9, 60, 5, 0, 0, 0, 0, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{3 POTES - LIPOTIDE,6 POTES - LIPOTIDE,1 POTE - LIPOTIDE}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD37-TEC', 0, 0, 0, 13.75, -13.75, -13.75, 0, 0, 0.7639, 0, 18, 0, 16, 0, 0, 0, 0, 0, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD60-TEC', 0, 0, 0, 13.75, -13.75, -13.75, 0, 0, 0.7639, 1, 18, 94.4, 18, 1, 0, 0, 0, 0, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{1 POTE - LIPOTIDE}', '{United Kingdom}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD42-UK', 0, 0, 0, 120.72, -120.72, -120.72, 0, 0, 0.7641, 4, 158, 97.5, 155, 4, 0, 0, 0, 0, '{GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE,LIPOTIDE - PERFECTPAY}', '{1 POTE - LIPOTIDE,6 POTES - LIPOTIDE,3 POTES - LIPOTIDE}', '{United Kingdom,United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD1', 0, 0, 0, 79.31, -79.31, -79.31, 0, 0, 0.4749, 0, 167, 0, 105, 0, 0, 0, 0, 0, '{PF-JEFF (Jelly Lean),JELLY LEAN}', '{}', '{United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG08', 0, 0, 0, 57.46, -57.46, -57.46, 0, 0, 0.4749, 0, 121, 0, 100, 0, 0, 0, 0, 0, '{PF-JEFF (Jelly Lean),JELLY LEAN}', '{}', '{United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG07', 0, 0, 0, 71.23, -71.23, -71.23, 0, 0, 0.4749, 0, 150, 0, 118, 0, 0, 0, 0, 0, '{PF-JEFF (Jelly Lean),JELLY LEAN}', '{}', '{United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG06', 0, 0, 0, 22.32, -22.32, -22.32, 0, 0, 0.4749, 1, 47, 97.9, 42, 1, 0, 0, 0, 0, '{PF-JEFF (Jelly Lean),JELLY LEAN}', '{JellyLean 6 bottles}', '{United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG05', 0, 0, 0, 53.66, -53.66, -53.66, 0, 0, 0.4749, 0, 113, 0, 92, 0, 0, 0, 0, 0, '{PF-JEFF (Jelly Lean),JELLY LEAN}', '{}', '{United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG04', 0, 0, 0, 159.56, -159.56, -159.56, 0, 0, 0.4749, 2, 336, 99.4, 271, 2, 0, 0, 0, 0, '{PF-JEFF (Jelly Lean),JELLY LEAN}', '{JellyLean 2 bottles,JellyLean 6 bottles}', '{United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG03', 0, 0, 0, 76.93, -76.93, -76.93, 0, 0, 0.4749, 4, 162, 97.5, 145, 4, 0, 0, 0, 0, '{PF-JEFF (Jelly Lean),JELLY LEAN}', '{JellyLean 6 bottles,JellyLean 3 bottles}', '{United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('IMG01', 0, 0, 0, 123.47, -123.47, -123.47, 0, 0, 0.4749, 1, 260, 99.6, 224, 1, 0, 0, 0, 0, '{PF-JEFF (Jelly Lean),JELLY LEAN}', '{JellyLean 6 bottles}', '{United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD2', 0, 0, 0, 82.63, -82.63, -82.63, 0, 0, 0.4749, 0, 174, 0, 113, 0, 0, 0, 0, 0, '{PF-JEFF (Jelly Lean),JELLY LEAN}', '{}', '{United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD08', 0, 0, 0, 34.67, -34.67, -34.67, 0, 0, 0.4749, 0, 73, 0, 45, 0, 0, 0, 0, 0, '{PF-JEFF (Jelly Lean),JELLY LEAN}', '{}', '{United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD07', 0, 0, 0, 35.14, -35.14, -35.14, 0, 0, 0.4749, 0, 74, 0, 39, 0, 0, 0, 0, 0, '{PF-JEFF (Jelly Lean),JELLY LEAN}', '{}', '{United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD06', 0, 0, 0, 29.44, -29.44, -29.44, 0, 0, 0.4748, 0, 62, 0, 42, 0, 0, 0, 0, 0, '{PF-JEFF (Jelly Lean),JELLY LEAN}', '{}', '{United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD05_P1_B05_HK05', 0, 0, 0, 12.82, -12.82, -12.82, 0, 0, 0.4748, 0, 27, 0, 24, 0, 0, 0, 0, 0, '{PF-JEFF (Jelly Lean),JELLY LEAN}', '{}', '{United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD05', 0, 0, 0, 31.82, -31.82, -31.82, 0, 0, 0.4749, 0, 67, 0, 34, 0, 0, 0, 0, 0, '{PF-JEFF (Jelly Lean),JELLY LEAN}', '{}', '{United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD04', 0, 0, 0, 92.6, -92.6, -92.6, 0, 0, 0.4749, 0, 195, 0, 123, 0, 0, 0, 0, 0, '{PF-JEFF (Jelly Lean),JELLY LEAN}', '{}', '{United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD03', 0, 0, 0, 88.81, -88.81, -88.81, 0, 0, 0.4749, 1, 187, 99.5, 124, 1, 0, 0, 0, 0, '{PF-JEFF (Jelly Lean),JELLY LEAN}', '{JellyLean 2 bottles}', '{United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD02_P1_B02_HK02', 0, 0, 0, 2.37, -2.37, -2.37, 0, 0, 0.474, 0, 5, 0, 4, 0, 0, 0, 0, 0, '{PF-JEFF (Jelly Lean),JELLY LEAN}', '{}', '{United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('AD01_P1_B01_HK01', 0, 0, 0, 1.9, -1.9, -1.9, 0, 0, 0.475, 0, 4, 0, 3, 0, 0, 0, 0, 0, '{PF-JEFF (Jelly Lean),JELLY LEAN}', '{}', '{United States}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO creatives (creative, purchases, revenue_usd, revenue_brl, spend_usd, gross_profit, profit_usd, roas, cpa, cpc, ics, clicks, bounce_rate, landing_views, landing_clicks, conversion_rate, ic_to_purchase_rate, avg_ticket, lead_to_purchase_cvr, campaigns, products, countries, updated_at)
    VALUES ('N/A', 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1, 0, 0, 0, 0, 0, 0, 0, '{LIPOTIDE - PERFECTPAY,JELLY LEAN}', '{1 POTE - LIPOTIDE,JellyLean 6 bottles}', '{Portugal}', NOW())
    ON CONFLICT (creative) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd, revenue_brl = EXCLUDED.revenue_brl, spend_usd = EXCLUDED.spend_usd, profit_usd = EXCLUDED.profit_usd, roas = EXCLUDED.roas, updated_at = NOW();
INSERT INTO purchases (purchase_id, lead_id, creative, campaign, product, currency, value_usd, value_brl, value_gbp, value_eur, value_cad, sub4, sub5, sub7, country, country_code, device_type, device_model, browser, landing, offer_name, traffic_channel, purchased_at)
    VALUES ('16', '5944', 'AD8-UK', 'LIPOTIDE - PERFECTPAY', 'Lipotide', 'USD', 200, 1034.97, 149.41, 173.06, 278.85, 'USDL1-CP13 - 1-1-1 - 10/06/26 - AD8-UK - ISABELA COLLINS', 'UK +20 - WOMAN', 'ig', 'United Kingdom', 'GB', 'Mobile', 'Galaxy S20 FE', 'Instagram 432.1', '(LIPOTIDE) VSL', '6 POTES - LIPOTIDE', 'GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE', '2026-06-10 09:53:26')
    ON CONFLICT (purchase_id) DO UPDATE SET creative = EXCLUDED.creative, value_usd = EXCLUDED.value_usd;
INSERT INTO purchases (purchase_id, lead_id, creative, campaign, product, currency, value_usd, value_brl, value_gbp, value_eur, value_cad, sub4, sub5, sub7, country, country_code, device_type, device_model, browser, landing, offer_name, traffic_channel, purchased_at)
    VALUES ('15', '5878', 'AD37-UK', 'LIPOTIDE - PERFECTPAY', 'Lipotide', 'USD', 200, 1035.42, 149.51, 173.14, 279.07, 'USDL1-CP9 - 1-1-1 - 06/06/26 - AD37-UK - CAT', 'UK +20 - WOMAN', 'fb', 'United Kingdom', 'GB', 'Tablet', 'iPad 10 10.9" WiFi', 'Facebook 564', '(LIPOTIDE) VSL', '6 POTES - LIPOTIDE', 'GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE', '2026-06-10 05:51:49')
    ON CONFLICT (purchase_id) DO UPDATE SET creative = EXCLUDED.creative, value_usd = EXCLUDED.value_usd;
INSERT INTO purchases (purchase_id, lead_id, creative, campaign, product, currency, value_usd, value_brl, value_gbp, value_eur, value_cad, sub4, sub5, sub7, country, country_code, device_type, device_model, browser, landing, offer_name, traffic_channel, purchased_at)
    VALUES ('13', '3163', 'IMG02', 'JELLY LEAN', 'JellyLean 6 bottles', 'USD', 220, 1115.69, 163.52, 188.75, 306.01, '0073-CP1-JELLY-IMG02', 'CJ1-USA-9-WOMAN-20+', 'th', 'United States', 'US', 'Mobile', 'iPhone 16 Plus', 'Threads 432.1', '(JELLY LEAN) VSL3-ML2', 'JellyLean 6 bottles', 'PF-JEFF (Jelly Lean)', '2026-06-07 22:59:12')
    ON CONFLICT (purchase_id) DO UPDATE SET creative = EXCLUDED.creative, value_usd = EXCLUDED.value_usd;
INSERT INTO purchases (purchase_id, lead_id, creative, campaign, product, currency, value_usd, value_brl, value_gbp, value_eur, value_cad, sub4, sub5, sub7, country, country_code, device_type, device_model, browser, landing, offer_name, traffic_channel, purchased_at)
    VALUES ('12', '3161', 'AD37-UK', 'LIPOTIDE - PERFECTPAY', 'Lipotide', 'USD', 200, 1017.69, 148.86, 171.78, 279.08, 'USDL1-CP9 - 1-1-1 - 06/06/26 - AD37-UK - CAT', 'UK +20 - WOMAN', 'fb', 'United Kingdom', 'GB', 'Mobile', 'Galaxy A6', 'Facebook 564', '(LIPOTIDE) VSL', '3 POTES - LIPOTIDE', 'GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE', '2026-06-07 22:23:05')
    ON CONFLICT (purchase_id) DO UPDATE SET creative = EXCLUDED.creative, value_usd = EXCLUDED.value_usd;
INSERT INTO purchases (purchase_id, lead_id, creative, campaign, product, currency, value_usd, value_brl, value_gbp, value_eur, value_cad, sub4, sub5, sub7, country, country_code, device_type, device_model, browser, landing, offer_name, traffic_channel, purchased_at)
    VALUES ('11', '3155', 'AD9-UK', 'LIPOTIDE - PERFECTPAY', 'Lipotide', 'USD', 200, 1017.69, 148.86, 171.78, 279.08, 'USDL1-CP8 - 1-1-1 - 05/06/26 - AD9-UK - ISABELA COLLINS', 'UK +20 - WOMAN', 'fb', 'United Kingdom', 'GB', 'Mobile', 'iPhone 14', 'Facebook 564', '(LIPOTIDE) VSL', '6 POTES - LIPOTIDE', 'GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE', '2026-06-07 22:14:21')
    ON CONFLICT (purchase_id) DO UPDATE SET creative = EXCLUDED.creative, value_usd = EXCLUDED.value_usd;
INSERT INTO purchases (purchase_id, lead_id, creative, campaign, product, currency, value_usd, value_brl, value_gbp, value_eur, value_cad, sub4, sub5, sub7, country, country_code, device_type, device_model, browser, landing, offer_name, traffic_channel, purchased_at)
    VALUES ('10', '2018', 'AD60-UK', 'LIPOTIDE - PERFECTPAY', 'Lipotide', 'USD', 200, 1013.96, 148.61, 171.72, 278.47, 'USDL1-CP11 - 1-1-1 - 06/06/26 - AD602-UK - CAT', 'UK +20 - WOMAN', 'fb', 'United Kingdom', 'GB', 'Mobile', 'iPhone 11', 'Facebook 564', '(LIPOTIDE) VSL', '6 POTES - LIPOTIDE', 'GIANT METRIX - PRABHAT I FACEBOOK I PERFIL 02 ANUNCIANTE', '2026-06-06 15:13:05')
    ON CONFLICT (purchase_id) DO UPDATE SET creative = EXCLUDED.creative, value_usd = EXCLUDED.value_usd;
INSERT INTO daily_metrics (date, clicks, ics, purchases, revenue_usd, revenue_brl, unique_creatives, conversion_rate)
    VALUES ('2026-06-06', 471, 0, 1, 200, 1013.96, 1, 0)
    ON CONFLICT (date) DO UPDATE SET clicks = EXCLUDED.clicks, purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd;
INSERT INTO daily_metrics (date, clicks, ics, purchases, revenue_usd, revenue_brl, unique_creatives, conversion_rate)
    VALUES ('2026-06-07', 703, 0, 3, 620, 3151.07, 3, 0)
    ON CONFLICT (date) DO UPDATE SET clicks = EXCLUDED.clicks, purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd;
INSERT INTO daily_metrics (date, clicks, ics, purchases, revenue_usd, revenue_brl, unique_creatives, conversion_rate)
    VALUES ('2026-06-10', 194, 0, 2, 400, 2070.3900000000003, 2, 0)
    ON CONFLICT (date) DO UPDATE SET clicks = EXCLUDED.clicks, purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd;
INSERT INTO offers (offer_id, name, checkout, product, clicks, landing_clicks, total_spent, total_revenue, total_purchase, roas, roi, cpa, cpc, gross_profit, avg_ticket, funnel_conversion, epc, purchase_count_api, purchase_value_api)
    VALUES (6, '6 POTES - LIPOTIDE', 'PERFECTPAY CUSTOM', '6 POTES - LIPOTIDE', 27, 27, 20.63, 1296.2, 6, 62.830829, 6183.082889, 3.438333, 0.764074, 1275.57, 216.033333, 0, 0, 0, 0)
    ON CONFLICT (offer_id) DO UPDATE SET name = EXCLUDED.name, total_spent = EXCLUDED.total_spent, total_revenue = EXCLUDED.total_revenue;
INSERT INTO offers (offer_id, name, checkout, product, clicks, landing_clicks, total_spent, total_revenue, total_purchase, roas, roi, cpa, cpc, gross_profit, avg_ticket, funnel_conversion, epc, purchase_count_api, purchase_value_api)
    VALUES (3, 'JellyLean 6 bottles', 'DIGISTORE - JELLY LEAN', 'JellyLean 6 bottles', 10, 10, 4.75, 220, 1, 46.315789, 4531.578947, 4.75, 0.475, 215.25, 220, 0, 0, 0, 0)
    ON CONFLICT (offer_id) DO UPDATE SET name = EXCLUDED.name, total_spent = EXCLUDED.total_spent, total_revenue = EXCLUDED.total_revenue;
INSERT INTO offers (offer_id, name, checkout, product, clicks, landing_clicks, total_spent, total_revenue, total_purchase, roas, roi, cpa, cpc, gross_profit, avg_ticket, funnel_conversion, epc, purchase_count_api, purchase_value_api)
    VALUES (5, '3 POTES - LIPOTIDE', 'PERFECTPAY CUSTOM', '3 POTES - LIPOTIDE', 17, 17, 12.99, 400, 2, 30.792918, 2979.291763, 6.495, 0.764118, 387.01, 200, 0, 0, 0, 0)
    ON CONFLICT (offer_id) DO UPDATE SET name = EXCLUDED.name, total_spent = EXCLUDED.total_spent, total_revenue = EXCLUDED.total_revenue;
INSERT INTO offers (offer_id, name, checkout, product, clicks, landing_clicks, total_spent, total_revenue, total_purchase, roas, roi, cpa, cpc, gross_profit, avg_ticket, funnel_conversion, epc, purchase_count_api, purchase_value_api)
    VALUES (4, '1 POTE - LIPOTIDE', 'PERFECTPAY CUSTOM', '1 POTE - LIPOTIDE', 11, 11, 8.4, 0, 0, 0, -100, 0, 0.763636, -8.4, 0, 0, 0, 0, 0)
    ON CONFLICT (offer_id) DO UPDATE SET name = EXCLUDED.name, total_spent = EXCLUDED.total_spent, total_revenue = EXCLUDED.total_revenue;
INSERT INTO offers (offer_id, name, checkout, product, clicks, landing_clicks, total_spent, total_revenue, total_purchase, roas, roi, cpa, cpc, gross_profit, avg_ticket, funnel_conversion, epc, purchase_count_api, purchase_value_api)
    VALUES (1, 'JellyLean 2 bottles', 'DIGISTORE - JELLY LEAN', 'JellyLean 2 bottles', 2, 2, 0.95, 0, 0, 0, -100, 0, 0.475, -0.95, 0, 0, 0, 0, 0)
    ON CONFLICT (offer_id) DO UPDATE SET name = EXCLUDED.name, total_spent = EXCLUDED.total_spent, total_revenue = EXCLUDED.total_revenue;
INSERT INTO offers (offer_id, name, checkout, product, clicks, landing_clicks, total_spent, total_revenue, total_purchase, roas, roi, cpa, cpc, gross_profit, avg_ticket, funnel_conversion, epc, purchase_count_api, purchase_value_api)
    VALUES (2, 'JellyLean 3 bottles', 'DIGISTORE - JELLY LEAN', 'JellyLean 3 bottles', 1, 1, 0.47, 0, 0, 0, -100, 0, 0.47, -0.47, 0, 0, 0, 0, 0)
    ON CONFLICT (offer_id) DO UPDATE SET name = EXCLUDED.name, total_spent = EXCLUDED.total_spent, total_revenue = EXCLUDED.total_revenue;
INSERT INTO country_stats (country, purchases, revenue_usd, clicks, ics, conversion_rate)
    VALUES ('United Kingdom', 5, 1000, 2446, 53, 0.2)
    ON CONFLICT (country) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd;
INSERT INTO country_stats (country, purchases, revenue_usd, clicks, ics, conversion_rate)
    VALUES ('United States', 1, 220, 2583, 12, 0.04)
    ON CONFLICT (country) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd;
INSERT INTO country_stats (country, purchases, revenue_usd, clicks, ics, conversion_rate)
    VALUES ('Portugal', 0, 0, 4, 3, 0)
    ON CONFLICT (country) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd;
INSERT INTO device_stats (device, purchases, revenue_usd, clicks)
    VALUES ('Mobile', 5, 1020, 4355)
    ON CONFLICT (device) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd;
INSERT INTO device_stats (device, purchases, revenue_usd, clicks)
    VALUES ('Tablet', 1, 200, 626)
    ON CONFLICT (device) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd;
INSERT INTO device_stats (device, purchases, revenue_usd, clicks)
    VALUES ('Desktop', 0, 0, 52)
    ON CONFLICT (device) DO UPDATE SET purchases = EXCLUDED.purchases, revenue_usd = EXCLUDED.revenue_usd;
UPDATE sync_log SET finished_at = NOW(), status = 'success', total_leads = 5030, total_purchases = 9, total_ics = 68 WHERE id = (SELECT max(id) FROM sync_log);
COMMIT;